ifndef XILINX_SDX
$(error Environment variable XILINX_SDX is required and should point to SDAccel install area)
endif

SDA_FLOW = cpu_emu
HOST_SRCS = test-cl.cpp
HOST_EXE_DIR=.
HOST_EXE = mmult_ex
HOST_CFLAGS = -g -Wall -DFPGA_DEVICE -DC_KERNEL 
HOST_LFLAGS = 

KERNEL_SRCS = mmult.cpp
KERNEL_NAME = mmult
KERNEL_DEFS = 
KERNEL_INCS = 
#set target device for XCLBIN
#XDEVICE=xilinx:adm-pcie-ku3:2ddr:3.3
XDEVICE=xilinx:adm-pcie-ku3:2ddr-xpr:4.0
XDEVICE_REPO_PATH=
KEEP_TEMP=1
KERNEL_DEBUG=
XCLBIN_NAME=bin_mmult
HOST_CFLAGS+=-DTARGET_DEVICE=\"${XDEVICE}\"
#BOARD_SETUP_FILE needs to point to setup.sh generated by xbinst command
BOARD_SETUP_FILE=setup.sh

ifeq (${SDA_FLOW},cpu_emu)
    CLCC_OPT += -t sw_emu
    XCLBIN = ${XCLBIN_NAME}_cpu_emu.xclbin
else ifeq (${SDA_FLOW},hw_emu)
    CLCC_OPT += -t hw_emu
    XCLBIN = ${XCLBIN_NAME}_hw_emu.xclbin
else ifeq (${SDA_FLOW},hw)
    XCLBIN = ${XCLBIN_NAME}_hw.xclbin
    CLCC_OPT += -t hw
endif

HOST_ARGS = ${XCLBIN}

COMMON_DIR = ${XILINX_SDX}/examples/common/
include ${COMMON_DIR}/common.mk

