# (C) Copyright 2016-2021 Xilinx, Inc.
# All Rights Reserved.
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License. 


#catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# Hls run script generated by the compiler
# 

#set xocc_optimize_level 0
open_project KERNEL_NAME
set_top KERNEL_NAME
add_files "KERNEL_SRC" -cflags " -D XILINX -I ./ KERNEL_FLAGS"
#add_files -tb
open_solution solution
set_part KERNEL_DEVICE
create_clock -period 300MHz -name default
#config_sdx -target xocc
#config_export -vivado_optimization_level $xocc_optimize_level
#config_dataflow -strict_mode warning
#set_clock_uncertainty 27.000000%
#config_interface -m_axi_addr64
config_export -format ip_catalog -ipname KERNEL_NAME
#csim_design
#csynth_design
#cosim_design
#export_design
close_project
exit
