
clean:
	-find . -name ".merlin_prj" -exec rm -rf {} \;
	-find . -name "*.log" -exec rm -rf {} \;
	-find . -name "log" -exec rm -rf {} \;
	-find . -name "*.rpt" -exec rm -rf {} \;
	-find . -name "*.mco" -exec rm -rf {} \;
	-find . -name "*.h" -exec rm -rf {} \;
	-find . -name "*.so" -exec rm -rf {} \;
	-find . -name "flex*" -exec rm -rf {} \;
	-find . -name ".merlin_prj" -exec rm -rf {} \;
	-find . -name ".finish_read_files" -exec rm -rf {} \;
	-find . -name ".Mer" -exec rm -rf {} \;
